#!/bin/bash

if [ -z "$1" ]; then
  echo "Error: A file name must be set, e.g. on \"the wonderful thing about tiggers\"."
  exit 1
fi

file_name=$(echo "$1" | tr ' ' '-')
formatted_file_name=$(date "+%Y_%m_%d")_${file_name}.md
#formatted_file_name=${file_name}.md
cd "$HOME/Documents/ZETTELKASTEN" || exit
touch "notes/${formatted_file_name}"
nvim "notes/${formatted_file_name}"
